Repository ietf-wg-cellar/matroska-specification, pull requests merged in 2019-10, with the labels that each got.

#344 Fix unicode symbol
  notes.md
Labels: formatting

#272 add implementation_notes on conditional element attributes
  ebml_matroska.xml
  transforms/ebml_schema2markdown4rfc.xsl
  transforms/schema_clean.xsl
Labels: clarifications, formatting, spec_main

#287 add BlockAdditionMapping to describe each BlockAdditional data
  Makefile
  block_additional_mappings_intro.md
  codec_specs.md
  ebml_matroska.xml
Labels: format addition, spec_main

#349 Update to xml2rfc version 3 processing
  .gitignore
  Makefile
  README.md
  bootstrap
  chapters.md
  codec/av1.md
  codec_specs.md
  diagram.md
  index_codec.md
  index_matroska.md
  index_tags.md
  matroska_tags.xml
  notes.md
  rfc_backmatter_codec.md
  rfc_backmatter_matroska.md
  rfc_backmatter_tags.md
  subtitles.md
  tools.mak
Labels: formatting
