Repository ietf-wg-cellar/matroska-specification, pull requests merged in 2020-08, with the labels that each got.

#402 turn definitions into definition lists
  index_matroska.md
Labels: formatting

#401 Use the EBML RFC as a normative reference
  index_matroska.md
Labels: clarifications

#404 mark RFC2119 keywords with **<>** to mmark turns them into BCP14 code
  attachments.md
  block_additional_mappings_intro.md
  chapters.md
  codec/av1.md
  codec_specs.md
  cues.md
  diagram.md
  ebml_matroska.xml
  index_matroska.md
  matroska_tags.xml
  menu.md
  notes.md
  ordering.md
  streaming.md
  subtitles.md
  tagging.md
Labels: formatting

#403 Direct EBML RFC sections
  index_matroska.md
Labels: clarifications

#407 Replace misc text (simple|double) quotes
  block_additional_mappings/smpte-st12-1-timecode.md
  block_additional_mappings_intro.md
  codec_specs.md
  ebml_matroska.xml
  index_matroska.md
  matroska_tags.xml
  notes.md
  subtitles.md
Labels: formatting

#413 update to mmark 2.2.9 which can properly sort references
  bootstrap
Labels: formatting

#415 fix subtitle bullet list formatting
  subtitles.md
Labels: formatting

#408 use the correct markdown for superscript text (power in equations)
  index_matroska.md
Labels: formatting

#410 remove USF from codecs
  codec_specs.md
  subtitles.md
Labels: bug, codec mapping

#411 Clean text references in the EBML schema
  ebml_matroska.xml
Labels: bug

#416 punctuation nits
  subtitles.md
Labels: formatting

#417 aesthetic nit
  bootstrap
Labels: build system

#418 fix punctuation nit
  index_matroska.md
Labels: formatting
