Repository ietf-wg-cellar/matroska-specification, pull requests merged in 2021-08, with the labels that each got.

#526 Fix typos of "identifier" and "interpretation"
  ebml_matroska.xml
Labels: bug, spec_main

#520 fix some Markdown formatting
  transforms/ebml_schema2markdown4rfc.xsl
  transforms/schema_clean.xsl
Labels: formatting

#531 nit: UK colours > US colors
  notes.md
Labels: bug, spec_main

#530 Add some encryption/compression links
  ebml_matroska.xml
  rfc_backmatter_matroska.md
Labels: enhancement, clarifications, spec_main

#536 use singular for the possibly multiple ChapLanguage/ChapCountry
  ebml_matroska.xml
Labels: clarifications, spec_main
