Repository ietf-wg-cellar/matroska-specification, pull requests merged in 2021-09, with the labels that each got.

#559 fix normative SHOULD usage
  ebml_matroska.xml
  index_matroska.md
  subtitles.md
  tagging.md
Labels: bug, formatting, spec_main

#561 fix SHOULD NOT normative text in deprecated IDs
  iana.md
Labels: bug, formatting, spec_main

#560 reorder some attributes to have consistent parameter order
  ebml_matroska.xml
Labels: formatting, XML Schema

#562 remove legacy text about default values
  notes.md
Labels: bug, clarifications, spec_main

#567 dvvC typo fix
  codec_specs.md
Labels: bug, spec_codecs
