Repository ietf-wg-cellar/matroska-specification, pull requests merged in 2022-01, with the labels that each got.

#573 avs3 (IEEE 1857.10) video codec mapping
  codec_specs.md
  rfc_backmatter_codec.md
Labels: enhancement, spec_codecs

#575 Remove deprecated EncryptedBlock element from Cluster diagram
  diagram.md
Labels: bug, enhancement, spec_main

#576 Move Simpleblock section
  notes.md
Labels: clarifications, spec_main

#574 Remove duplicate rule on the placement of the Cluster Timestamp
  ordering.md
Labels: clarifications, spec_main

#579 fix the last sentence considered as a title
  index_matroska.md
Labels: bug, build system

#115 info on storing/using font files in attachments
  attachments.md
Labels: clarifications, spec_main

#556 Readd order of cropping and resizing
  notes.md
Labels: bug, clarifications

#558 make AlphaMode mandatory
  ebml_matroska.xml
Labels: bug, format addition, clarifications, spec_main
