Repository ietf-wg-cellar/matroska-specification, pull requests merged in 2023-05, with the labels that each got.

#753 fix timestamp typo
  notes.md
Labels: bug, spec_main

#762 Make the Tags position non normative
  ordering.md
Labels: clarifications, spec_main, ADReview

#764 Fix application instead of file reading in Matroska versioning
  notes.md
Labels: bug, clarifications, spec_main, ADReview

#763 Make non-RAP ReferenceBlock usage mandatory in BlockGroup
  notes.md
Labels: bug, clarifications, spec_main, ADReview

#765 Reword the DefaultDecodedFieldDuration to clarify the progressive value
  notes.md
Labels: bug, clarifications, spec_main, ADReview

#767 list change controller as IETF, rather than IESG
  iana.md
Labels: bug, clarifications, spec_main

#750 add missing CELLAR email in IANA
  iana.md
Labels: bug, spec_main

#768 list ID change controller as IETF, rather than IESG
  iana_matroska_ids.md
Labels: bug, clarifications, spec_main

#771 Separate Cropping example and remove normative text
  notes.md
Labels: formatting, clarifications, spec_main, ADReview

#772 Refer to a Segment within the chain
  notes.md
Labels: clarifications, spec_main, ADReview

#773 Combined tracks use the union of Cues
  notes.md
Labels: clarifications, spec_main, ADReview

#784 Use normative reference to ITU-H.273
  ebml_matroska.xml
  rfc_backmatter_matroska.md
Labels: clarifications, spec_main, ADReview

#777 Suggest restriction of fonts with AttachmentLink
  attachments.md
Labels: clarifications, spec_main, ADReview

#778 Add a link to recommendations for file access
  streaming.md
Labels: clarifications, spec_main, ADReview

#785 The Private encryption scope is the CodecPrivate data
  ebml_matroska.xml
Labels: clarifications, spec_main, ADReview

#774 Use normative MAY to support old files with stereo video
  notes.md
Labels: formatting, clarifications, spec_main, ADReview

#775 Add a reference to tags when using ORIGINAL_MEDIA_TYPE
  chapters.md
Labels: clarifications, spec_main, ADReview

#776 Add non normative references to JPEG and PNG
  attachments.md
  rfc_backmatter_matroska.md
Labels: clarifications, spec_main, ADReview

#782 Discourage the use of DES, 3DES and Blowfish
  ebml_matroska.xml
Labels: enhancement, spec_main, ADReview

#781 Turn the may occur in Segment non normative
  diagram.md
Labels: clarifications, spec_main, ADReview

#780 Clarify the recommended limit for Clusters
  matroska_implement.md
Labels: clarifications, spec_main, ADReview

#786 Add more security considerations from Roman Danyliw
  matroska_security.md
Labels: clarifications, spec_main, ADReview

#783 Do not use the attachement if it can't be checked
  matroska_security.md
Labels: clarifications, spec_main, ADReview

#787 Add a section on error handling in Security Considerations
  matroska_security.md
Labels: enhancement, spec_main, ADReview

#779 Use file-like protocol for live streaming
  streaming.md
Labels: clarifications, spec_main, ADReview
