Repository ietf-wg-cellar/matroska-specification, pull requests merged in 2023-10, with the labels that each got.

#800 Use C binary notation for lacing bits
  notes.md
Labels: clarifications, spec_main, ADReview

#799 Add the RFC8794 sections on which the errata apply
  index_matroska.md
Labels: bug, clarifications, spec_main, ADReview

#802 bump Matroska draft version after 2023-10-08 v20 tag
  Makefile
Labels: spec_main, build system

#808 Add links to EBML/Matroska RFC in security considerations
  codec_security.md
  index_chapter_codecs.md
  index_control.md
  tags_security.md
Labels: enhancement, clarifications, spec_tags, spec_codecs, spec_chapter_codec

#809 rename "old parsers"
  index_matroska.md
Labels: clarifications, spec_main

#804 Contact the IANA for new tags not the Matroska team
  tagging.md
Labels: bug, spec_tags

#810 Mention that default attributes in the Schema are omitted
  matroska_schema_section_header.md
Labels: clarifications, spec_main

#811 bump Matroska draft version after 2023-10-22 v20 tag
  Makefile
Labels: spec_main, build system

#812 bump Tags draft version after 2023-10-22 v12 tag
  Makefile
Labels: spec_tags, build system

#814 CueTime in Segment Ticks instead of Matroska Ticks
  ebml_matroska.xml
  notes.md
Labels: bug, spec_main
