Repository ietf-wg-cellar/matroska-specification, pull requests merged in 2024-04, with the labels that each got.

#820 Add codec mapping for VVC
  codec_specs.md
Labels: spec_codecs

#821 Fix mishandled list
  _includes/sidebar.html
Labels: website

#815 fix CueRefTime type
  ebml_matroska.xml
  notes.md
Labels: bug, spec_main, AUTH48

#819 Adjust FieldOrder enum labels to better match description texts
  ebml_matroska.xml
Labels: bug, spec_main, AUTH48
