Repository ietf-wg-cellar/matroska-specification, pull requests merged in 2024-09, with the labels that each got.

#841 fix (other) ommitted typo
  block_additional_mappings_intro.md
Labels: bug, spec_codecs

#840 fix typo
  LICENSE.md
Labels: bug

#837 forbid some mandatory elements to have a 0 value
  ebml_matroska.xml
Labels: enhancement, spec_main

#842 fix typo
  tagging.md
Labels: bug, spec_tags

#843 Revert "set the RFC9559 header"
  index_matroska.md
Labels: spec_main, build system, AUTH48

#845 bump Matroska draft version after 2024-09-12 v23 tag
  Makefile
Labels: spec_main, build system
