Repository ietf-wg-cellar/matroska-specification, pull requests merged in 2025-06, with the labels that each got.

#995 BlockAddIDValue 4 is not recommended
  cellar-codec/block_additional_mappings_intro.md
Labels: enhancement, spec_codecs

#1016 Fix a sample blockmoreid
  cellar-codec/block_additional_mappings_intro.md
Labels: bug, clarifications, spec_codecs

#1018 bump Codec draft version after 2025-06-29 v15 tag
  Makefile
Labels: spec_codecs, build system

#1022 fix "in in" typos
  cellar-tags/index_tags.md
Labels: bug, spec_tags, ADReview
